.othersProjects/merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # MY VIEWS
    # Model Band
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:band_id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:band_id>/update/', views.band_update, name='band-update'),
    path('bands/<int:band_id>/delete/', views.band_delete, name='band-delete'),

    # others
    path('about-us/', views.about, name='about-us'),

    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:listing_id>/', views.listing_detail, name='listing-detail'),
    path('listings/add/', views.listing_create, name='listing-create'),
    path('listings/<int:listing_id>/update/', views.listing_update, name='listing-update'),
    path('listings/<int:listing_id>/delete/', views.listing_delete, name='listing-delete'),

    path('contact-us/', views.contact, name='contact-us'),
    path('email-sent/', views.email_sent, name='email-sent'),
]

blog/urls.py
from django.urls import path

from . import views
from .apps import BlogConfig
from . import views

app_name = BlogConfig.name

urlpatterns = [

    path('', views.home, name='blog'),
    path('home/', views.home, name='home'),
    path('photo-feed/', views.photo_feed, name='photo_feed'),
    path('photo/upload/', views.photo_upload, name='photo_upload'),
    path('blog/create', views.blog_and_photo_upload, name='blog_create'),
    path('blog/<int:blog_id>', views.view_blog, name='view_blog'),
    path('blog/<int:blog_id>/edit', views.edit_blog, name='edit_blog'),
    path('photo/upload-multiple/', views.create_multiple_photos,
         name='create_multiple_photos'),
    path('follow-users/', views.follow_users, name='follow_users'),

]

fotoblog/urls.py
from faulthandler import is_enabled

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # login
    path('', include('authentication.urls'), name='home'),

    # APPS DASHBOARD
    # path('apps/', include('app_installer.urls'), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

.othersProjects/merchex/listings/models.py
from contextlib import nullcontext

from django.db import models
from django.db.models import fields
from django.core.validators import MaxValueValidator, MinValueValidator

class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
        GOSPEL = 'GP'
        SLOW = 'SL'

    name = fields.CharField(max_length=100)
    genre = fields.CharField(choices=Genre.choices, max_length=10)
    biography = fields.CharField(max_length=1000)
    year_formed = fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2024)]
    )
    active = fields.BooleanField(default=True)
    official_homepage = fields.URLField(null=True, blank=True)

    # manual error
    # limited_edition = fields.BooleanField(default=False)

    def __str__(self):
        return f"{self.name}"

class Listing(models.Model):
    class Type(models.TextChoices):
        RECORDS = "REC"
        CLOTHING = "CLO"
        POSTERS = "POS"
        MISCELLANEOUS = "MIS"

    title = fields.CharField(max_length=100)
    description = fields.CharField(max_length=1000)
    sold = fields.BooleanField(default=False)
    year = fields.IntegerField(
        validators=[MinValueValidator(1700), MaxValueValidator(2024)],
        null=True,
        blank=True
    )

    type = fields.CharField(choices=Type.choices, max_length=5)

    # Foreign Keys
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

    # manual error
    # limited_edition = fields.BooleanField(default=False)
    # antiquity = fields.BooleanField(default=False)

.othersProjects/merchex/listings/forms.py
from django import forms
from listings.models import Band, Listing

class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        # fields = '__all__'
        exclude = ('active', 'official_homepage')

class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing

        exclude = ('sold', )

.othersProjects/merchex/listings/views.py
from idlelib.rpc import response_queue

from django.http import HttpResponse
from django.shortcuts import render, redirect

from django.core.mail import send_mail

from listings.models import Band
from listings.models import Listing
from listings.forms import ContactUsForm, BandForm, ListingForm


def band_list(request):
    bands = Band.objects.all()

    return render(request,
                  'listings/band_list.html',
                  {
                      "bands": bands,
                  })


def band_detail(request, band_id):
    band = Band.objects.get(id=band_id)

    return render(request,
                  'listings/band_detail.html',
                  {
                      'band_id': band_id,
                      'band': band,
                  })

def band_create(request):
    band_form = None

    if request.method == 'POST':

        band_form = BandForm(request.POST)

        if band_form.is_valid():
            # create an instance of Band
            band = band_form.save()

            return redirect('band-detail', band.id)

        else:
            pass
    else:
        band_form = BandForm()

    return render(request,
                  'listings/band_create.html',
                  {'band_form': band_form})

def band_update(request, band_id):
    band = Band.objects.get(id=band_id)

    band_form = None

    if request.method == 'POST':

        band_form = BandForm(request.POST, instance=band)

        if band_form.is_valid():
            # create an instance of Band
            band = band_form.save()

            return redirect('band-detail', band.id)

        else:
            pass
    else:
        band_form = BandForm(instance=band)

    return render(request,
                  'listings/band_update.html',
                  {
                      'band_id': band_id,
                      'band_form': band_form,
                  })

def band_delete(request, band_id):
    band = Band.objects.get(id=band_id)

    if request.method == 'POST':
        band.delete()

        return redirect('band-list')
    else:
        pass

    return render(request,
                  'listings/band_delete.html',
                  {
                      'band_id': band_id,
                      'band': band,
                  })

def listing_update(request, listing_id):
    listing = Listing.objects.get(id=listing_id)

    listing_form = None

    if request.method == 'POST':

        listing_form = ListingForm(request.POST, instance=listing)

        if listing_form.is_valid():
            # create an instance of Band
            listing = listing_form.save()

            return redirect('listing-detail', listing.id)

        else:
            pass
    else:
        listing_form = ListingForm(instance=listing)

    return render(request,
                  'listings/listing_update.html',
                  {
                      'listing_id': listing_id,
                      'listing_form': listing_form,
                  })

def listing_delete(request, listing_id):
    listing = Listing.objects.get(id=listing_id)

    if request.method == 'POST':
        listing.delete()

        return redirect('listing-list')
    else:
        pass

    return render(request,
                  'listings/listing_delete.html',
                  {
                      'listing_id': listing_id,
                      'listing': listing,
                  })

def about(request):
    return render(request,
                  'listings/about.html', )


def listing_list(request):
    listings = Listing.objects.all()

    return render(request,
                  'listings/listing_list.html',
                  {'listings': listings}, )

def listing_detail(request, listing_id):
    listing = Listing.objects.get(id=listing_id)

    return render(request,
                  'listings/listing_detail.html',
                  {
                      'listing_id': listing_id,
                      'listing': listing,
                  })

def listing_create(request):
    listing_form = None

    if request.method == 'POST':

        listing_form = ListingForm(request.POST)

        if listing_form.is_valid():
            # create an instance of Band
            listing = listing_form.save()

            return redirect('listing-detail', listing.id)

        else:
            pass
    else:
        listing_form = ListingForm()

    return render(request,
                  'listings/listing_create.html',
                  {'listing_form': listing_form})

def contact(request):

    # logging
    print ("Request Method : ", request.method)
    print("Request Post Datas: ", request.POST)

    form = None # formulaire

    if request.method == 'POST':
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f"Message from {form.cleaned_data['name'] or 'anonyme'} via Merchex Contact Form",
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )

            return redirect('email-sent')
    else:
        form = ContactUsForm()

    return render(request,
                  'listings/contact.html',
                  {'form': form})

def email_sent(request):
    return render(request,
                  'listings/email_sent.html')

.othersProjects/merchex/listings/templates/listings/about.html
{% extends "listings/base.html" %}

{% block content %}

<h1>About Us</h1>
<p>We revolutionize backend development</p>

{% endblock %}

.othersProjects/merchex/listings/templates/listings/band_create.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Create new Band</h1>



<form action="" method="post">
 {% csrf_token %}
 {{ band_form.as_p }}
 <input type="submit" value="Envoyer">
</form>

{% endblock %}

.othersProjects/merchex/listings/templates/listings/band_delete.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Delete Band</h1>

<p>Are you sure you want to delete Band :  : {{ band.name }}</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Confirmer">
</form>

{% endblock %}

.othersProjects/merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ band.name }}</h2>
<ul>
    <li>Genre : {{ band.get_genre_display }}</li>
    <li>Annee de formation : {{band.year_formed}}</li>
    <li>Actif : {{ band.active|yesno }}</li>

    {% if band.official_homepage %}
    <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}></a></li>
    {% endif %}
</ul>

<p>{{ band.biography }}</p>

<h3>Band Listings</h3>
{% for listing in band.listing_set.all %}
    <li><a href="{% url 'listing-detail' listing.id %} ">{{ listing.title }}</a></li>
{% endfor %}

<p>
    <a href="{% url 'band-update' band.id %}">Edit this band</a>
    <a href="{% url 'band-delete' band.id %}">Delete this band</a>

    <a href="{% url 'band-list' %}">Retourner a tous les groupes</a>
</p>

{% endblock %}

.othersProjects/merchex/listings/templates/listings/band_list.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Groupes</h1>

<ul>
 {% for band in bands %}
  <li>
      <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
      - <a href="{% url 'band-update' band.id %}">[Edit]</a>
  </li>
 {% endfor %}
</ul>

<p>
    <a href="{% url 'band-create' %}">Ajouter un nouveau groupe</a>
</p>

{% endblock %}

.othersProjects/merchex/listings/templates/listings/band_update.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Update Band : {{ band_id }}</h1>

<form action="" method="post">
    {% csrf_token %}

    {{ band_form.as_p }}

    <input type="submit" value="Envoyer">
</form>

{% endblock %}

.othersProjects/merchex/listings/templates/listings/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Merchex</title>
    <!--        <link rel="stylesheet" href="{% static 'listings/style.css' %}"/>-->
</head>
<body>
<nav>
    <a href="{% url 'band-list' %}">Bands</a>
    <a href="{% url 'listing-list' %}">Listings</a>
    <a href="{% url 'contact-us' %}">Contact Us</a>
</nav>
{% block content %}{% endblock %}
</body>
</html>

.othersProjects/merchex/listings/templates/listings/contact.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Contact Us</h1>
<p>Nous sommes la pour vous aider</p>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

.othersProjects/merchex/listings/templates/listings/email_sent.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Contact Us</h1>
<p>Merci de nous avoir contacte, nous apprecions.</p>

{% endblock %}

.othersProjects/merchex/listings/templates/listings/listing_create.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Create new Band</h1>



<form action="" method="post">
 {% csrf_token %}
 {{ listing_form.as_p }}
 <input type="submit" value="Envoyer">
</form>

{% endblock %}

.othersProjects/merchex/listings/templates/listings/listing_delete.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Delete Listing</h1>

<p>Are you sure you want to delete Listing : {{ listing.title }}</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Confirmer">
</form>

{% endblock %}

.othersProjects/merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ listing.title }}</h2>
<ul>
    <li>Type : {{ listing.get_type_display }}</li>
    {% if listing.band %}
    <li><a href="{% url 'band-detail' listing.band.id %}">Band : {{ listing.band }}</a></li>
    {% endif %}
    <li>Annee de fabrication : {{listing.year}}</li>
    <li>Sold : {{ listing.sold|yesno }}</li>
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'listing-update' listing.id %}">Edit this listing</a>
<a href="{% url 'listing-delete' listing.id %}">Delete this listing</a>

<a href="{% url 'listing-list' %}">Retourner a tous les Listings</a>

{% endblock %}

.othersProjects/merchex/listings/templates/listings/listing_list.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Listings</h1>

<ul>
    {% for listing in listings %}
    <li>
        <a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a>
        - <a href="{% url 'listing-update' listing.id %}">[Edit]</a>

    </li>
    {% endfor %}
</ul>
<p>
    <a href="{% url 'listing-create' %}">Ajouter un nouveau listing</a>
</p>
{% endblock %}

.othersProjects/merchex/listings/templates/listings/listing_update.html
{% extends "listings/base.html" %}

{% block content %}

<h1>Update Listing : {{ listing_id }}</h1>

<form action="" method="post">
    {% csrf_token %}

    {{ listing_form.as_p }}

    <input type="submit" value="Envoyer">
</form>

{% endblock %}