.othersProjects/merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # MY VIEWS
    # Model Band
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:band_id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:band_id>/update/', views.band_update, name='band-update'),
    path('bands/<int:band_id>/delete/', views.band_delete, name='band-delete'),

    # others
    path('about-us/', views.about, name='about-us'),

    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:listing_id>/', views.listing_detail, name='listing-detail'),
    path('listings/add/', views.listing_create, name='listing-create'),
    path('listings/<int:listing_id>/update/', views.listing_update, name='listing-update'),
    path('listings/<int:listing_id>/delete/', views.listing_delete, name='listing-delete'),

    path('contact-us/', views.contact, name='contact-us'),
    path('email-sent/', views.email_sent, name='email-sent'),
]

app_installer/urls.py
from django.urls import path

from . import views

app_name = "app_installer"

urlpatterns = [
    path("", views.AppDashboardView.as_view(), name='app_dashboard'),
    path("install/<str:app_name>/", views.InstallAppView.as_view(), name='install_app'),
    path("uninstall/<str:app_name>/", views.UninstallAppView.as_view(), name='uninstall_app'),
    path("default-home/<str:app_name>/", views.DefaultAppHomeView.as_view(), name='default_home'),
    path("forbidden/<str:app_name>/", views.AppForbiddenView.as_view(), name='forbidden'),

]

blog/urls.py
from django.urls import path

from . import views
from .apps import BlogConfig
from . import views

app_name = BlogConfig.name

urlpatterns = [

    path('', views.home, name='blog'),
    path('home/', views.home, name='home'),
    path('photo-feed/', views.photo_feed, name='photo_feed'),
    path('photo/upload/', views.photo_upload, name='photo_upload'),
    path('blog/create', views.blog_and_photo_upload, name='blog_create'),
    path('blog/<int:blog_id>', views.view_blog, name='view_blog'),
    path('blog/<int:blog_id>/edit', views.edit_blog, name='edit_blog'),
    path('photo/upload-multiple/', views.create_multiple_photos,
         name='create_multiple_photos'),
    path('follow-users/', views.follow_users, name='follow_users'),

]

fotoblog/urls.py
from faulthandler import is_enabled

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # login
    path('', include('authentication.urls'), name='home'),

    # APPS DASHBOARD
    # path('apps/', include('app_installer.urls'), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from PIL import Image


class Photo(models.Model):
    image = models.ImageField()
    caption = models.CharField(max_length=128, blank=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

    IMAGE_MAX_SIZE = (800, 800)

    def resize_image(self):
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        image.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()


class Blog(models.Model):
    photo = models.ForeignKey(Photo, null=True, on_delete=models.SET_NULL, blank=True)
    title = models.CharField(max_length=128)
    content = models.CharField(max_length=5000)
    contributors = models.ManyToManyField(
        settings.AUTH_USER_MODEL, through='BlogContributor', related_name='contributions')
    date_created = models.DateTimeField(auto_now_add=True)
    starred = models.BooleanField(default=False)
    word_count = models.IntegerField(null=True)

    def _get_word_count(self):
        return len(self.content.split(' '))

    def save(self, *args, **kwargs):
        self.word_count = self._get_word_count()
        super().save(*args, **kwargs)


class BlogContributor(models.Model):
    contributor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    contribution = models.CharField(max_length=255, blank=True)

    class Meta:
        unique_together = ('contributor', 'blog')

templates/base.html
{% load static %}
<html>
    <head>
        <title>FotoBlog</title>
        <link rel="stylesheet" href="{% static 'app.css' %}">
    </head>
    <body>
        <div class="sidebar">
            <h1>FotoBlog</h1>
            {% if user.is_authenticated %}
                <p>Hey {{ user }}!</p>
                {% if user.profile_photo %}
                    <img class="avatar" src={{ user.profile_photo.url }}>
                {% else %}
                    <img class="avatar" src="{% static 'images/default_profile.png'%}">
                {% endif %}
                <p><a href="{% url 'app_installer:app_dashboard' %}">Home</a></p>
                <p><a href="{% url 'blog:photo_feed' %}">Photo Feed</a></p>
                {% if perms.blog.add_blog %}
                    <p><a href="{% url 'blog:blog_create' %}">Create Blog Post</a></p>
                {% endif %}
                {% if perms.blog.add_photo %}
                    <p><a href="{% url 'blog:photo_upload' %}">Upload Photo</a></p>
                    <p><a href="{% url 'blog:create_multiple_photos' %}">Upload Multiple Photos</a></p>
                {% endif %}
                <p><a href="{% url 'blog:follow_users' %}">Follow Users</a></p>
                <p><a href="{% url 'authentication:upload_profile_photo' %}">Change Profile Photo</a></p>
                <p><a href="{% url 'authentication:password_change' %}">Change Password</a></p>
                <form action="{% url 'authentication:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
            {% endif %}
        </div>
        <div class="main">
            {% block content %}{% endblock content %}
        </div>
    </body>
</html>